version: '3.4'

services:
  asplearning.postgres:
    image: postgres:latest

  asplearning.api:
    image: ${DOCKER_REGISTRY-}asplearningapi
    build:
      context: .
      dockerfile: Systems/ASPLearning.Api/Dockerfile
    depends_on:
      - asplearning.postgres
   
  asplearning.identity:
    image: ${DOCKER_REGISTRY-}asplearningidentity
    build:
      context: .
      dockerfile: Systems/ASPLearning.Identity/Dockerfile
    depends_on:
      - asplearning.postgres
      - asplearning.api