version: '3.4'

services:
  asplearning.postgres:
    env_file:
      - env.postgres
    ports:
      - "49153:5432"
    networks:
      - shared_asplearning
    volumes:
      - ~/.docker-conf/mssql/data/:/var/lib/mssql/data

  asplearning.api:
    ports:
      - "10000:80"
    env_file:
      - env.api

  asplearning.identity:
    ports:
      - "10001:80"
    env_file:
      - env.identity

networks:
  shared_asplearning:
    name: asplearing
    driver: bridge